### ISSUE TITLE
Water not passing through stacked hollow woods

### ISSUE THREAD

**Issue by ModMan2021** [costamiri/HollowWoods#1]
If  you put water in a hollow wood, it'll pass through and flow out, but if you have two hollow woods on top of each other, the water doesn't flow to the next hollow wood.

**Comment by costamiri** [comment]
Thats the intended behaviour. It is similar with open trapdoors, fences, etc. where the waterlogged status does not transfer from blocks above. As I don't want to introduce inconsistencies to vanilla minecraft this will not change with waterlogged logs.
