### ISSUE TITLE
Inconsistency in colors

### ISSUE THREAD

**Issue by EGOIST1372** [costamiri/HollowWoods#2]
Inconsistency in colors
all hollow woods are darker in colors
is it intentional to be darker or a bug? just curious 

example:
![image](https://user-images.githubusercontent.com/86555131/162827272-caec34e4-2664-40d8-8239-af7752d96a77.png)
![image](https://user-images.githubusercontent.com/86555131/162827683-18b28c8d-7076-4a77-8504-b7c73e125485.png)

**Comment by costamiri** [comment]
It's definitly a bug, a strange one on top of that, as the blocks simply reference the vanilla textures. Are you using a shader or visual mod that might affect this or does it still happen even without any mod/shader on?

**Comment by EGOIST1372** [comment]
no shader is active. it's vanilla 
and the only visual mod is [visual overhaul](https://www.curseforge.com/minecraft/mc-mods/visual-overhaul) mod that has nothing to do with woods/logs
and to be honest I actually like it. even if it's a bug I don't want it to be removed. just was curious about it that's it
